markdown: redcarpet
permalink: /:year/:month/:day/:title.html
lsi: false
highlighter: pygments
safe: false
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
title: 网魂的博客
description: 网魂的博客
feed: http://liuzhisheng.github.io/atom.xml

author: 刘志胜

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
